import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import "dotenv/config";

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const collegesData = [
  {
    name: "Indian Institute of Technology (IIT) Madras",
    city: "Chennai",
    state: "Tamil Nadu",
    nirfRank: 1,
    nirfScore: 89.42,
    fees: 220000,
    averagePackage: 2270000,
    rating: 4.9,
    overview: "Established in 1959, IIT Madras is a premier public technical and research university located in Chennai. It has been consistently ranked as the top engineering institute in India by NIRF.",
    establishedYear: 1959,
    website: "https://www.iitm.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Delhi",
    city: "New Delhi",
    state: "Delhi",
    nirfRank: 2,
    nirfScore: 87.31,
    fees: 225000,
    averagePackage: 2190000,
    rating: 4.8,
    overview: "IIT Delhi is a prominent public research university located in New Delhi. It is known for its distinguished faculty and strong industry partnerships, offering excellent academic and research facilities.",
    establishedYear: 1961,
    website: "https://home.iitd.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5c?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Bombay",
    city: "Mumbai",
    state: "Maharashtra",
    nirfRank: 3,
    nirfScore: 85.14,
    fees: 228000,
    averagePackage: 2180000,
    rating: 4.9,
    overview: "IIT Bombay, situated in Powai, Mumbai, was established in 1958. It is renowned globally for its cutting-edge research, startup incubation center, and top-tier placement packages.",
    establishedYear: 1958,
    website: "https://www.iitb.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Kanpur",
    city: "Kanpur",
    state: "Uttar Pradesh",
    nirfRank: 4,
    nirfScore: 83.22,
    fees: 215000,
    averagePackage: 1960000,
    rating: 4.8,
    overview: "IIT Kanpur was created in 1959. It is celebrated for its academic rigor, broad research initiatives, and massive residential campus equipped with its own airfield.",
    establishedYear: 1959,
    website: "https://www.iitk.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Kharagpur",
    city: "Kharagpur",
    state: "West Bengal",
    nirfRank: 5,
    nirfScore: 81.75,
    fees: 222000,
    averagePackage: 1890000,
    rating: 4.7,
    overview: "Founded in 1951, IIT Kharagpur is the oldest of all the IITs. It features the largest campus size and the maximum student enrollment among all premium institutes.",
    establishedYear: 1951,
    website: "https://www.iitkgp.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Roorkee",
    city: "Roorkee",
    state: "Uttarakhand",
    nirfRank: 6,
    nirfScore: 79.83,
    fees: 220000,
    averagePackage: 1820000,
    rating: 4.7,
    overview: "Established in 1847 as the Thomason College of Civil Engineering, IIT Roorkee is the oldest technical institution in Asia, boasting rich traditions and high placement records.",
    establishedYear: 1847,
    website: "https://www.iitr.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Guwahati",
    city: "Guwahati",
    state: "Assam",
    nirfRank: 7,
    nirfScore: 77.91,
    fees: 218000,
    averagePackage: 1750000,
    rating: 4.6,
    overview: "IIT Guwahati is situated on the banks of the majestic Brahmaputra River. It is known for its beautiful campus and state-of-the-art research centers in Biotechnology and Nanotechnology.",
    establishedYear: 1994,
    website: "https://www.iitg.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Trichy",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    nirfRank: 8,
    nirfScore: 73.44,
    fees: 145000,
    averagePackage: 1540000,
    rating: 4.6,
    overview: "NIT Trichy is ranked as the best National Institute of Technology in India. It is highly competitive, offering rich campus opportunities and exceptional academic program options.",
    establishedYear: 1964,
    website: "https://www.nitt.edu",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Hyderabad",
    city: "Sangareddy",
    state: "Telangana",
    nirfRank: 9,
    nirfScore: 72.82,
    fees: 223000,
    averagePackage: 1680000,
    rating: 4.5,
    overview: "IIT Hyderabad is celebrated for its strong research collaborations with Japanese universities and its unique, modern architecture situated in Kandi.",
    establishedYear: 2008,
    website: "https://www.iith.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Surathkal",
    city: "Mangaluru",
    state: "Karnataka",
    nirfRank: 10,
    nirfScore: 71.95,
    fees: 150000,
    averagePackage: 1480000,
    rating: 4.5,
    overview: "NIT Surathkal is unique in having its own private beach on the Arabian Sea coast. It is famed for its strong engineering programs and placement support.",
    establishedYear: 1960,
    website: "https://www.nitk.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Jadavpur University (Faculty of Engineering)",
    city: "Kolkata",
    state: "West Bengal",
    nirfRank: 11,
    nirfScore: 70.32,
    fees: 10000,
    averagePackage: 1120000,
    rating: 4.6,
    overview: "Jadavpur University's Engineering division is highly sought after due to its extremely low fee structure and high placement statistics, yielding an unmatched ROI in India.",
    establishedYear: 1955,
    website: "http://www.jaduniv.edu.in",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Vellore Institute of Technology (VIT)",
    city: "Vellore",
    state: "Tamil Nadu",
    nirfRank: 12,
    nirfScore: 69.81,
    fees: 195000,
    averagePackage: 920000,
    rating: 4.2,
    overview: "VIT Vellore is a leading private university offering world-class infrastructure, flexible credit systems, and highly structured career placements.",
    establishedYear: 1984,
    website: "https://vit.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Anna University",
    city: "Chennai",
    state: "Tamil Nadu",
    nirfRank: 13,
    nirfScore: 68.94,
    fees: 55000,
    averagePackage: 850000,
    rating: 4.3,
    overview: "Anna University is a premier state public university in Tamil Nadu, hosting the College of Engineering, Guindy, one of the oldest engineering colleges in the country.",
    establishedYear: 1978,
    website: "https://www.annauniv.edu",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) BHU",
    city: "Varanasi",
    state: "Uttar Pradesh",
    nirfRank: 14,
    nirfScore: 68.21,
    fees: 220000,
    averagePackage: 1780000,
    rating: 4.6,
    overview: "IIT BHU Varanasi is located inside the scenic campus of Banaras Hindu University. It is celebrated for its deep academic history and excellent alumni placements.",
    establishedYear: 1919,
    website: "https://www.iitbhu.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Dhanbad",
    city: "Dhanbad",
    state: "Jharkhand",
    nirfRank: 15,
    nirfScore: 67.53,
    fees: 210000,
    averagePackage: 1520000,
    rating: 4.4,
    overview: "Formerly known as Indian School of Mines (ISM), IIT Dhanbad was established in 1926 on the model of Royal School of Mines, London.",
    establishedYear: 1926,
    website: "https://www.iitism.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Rourkela",
    city: "Rourkela",
    state: "Odisha",
    nirfRank: 16,
    nirfScore: 66.82,
    fees: 140000,
    averagePackage: 1285000,
    rating: 4.4,
    overview: "NIT Rourkela is one of the premier national-level institutions, boasting extensive campus infrastructure and high academic standards.",
    establishedYear: 1961,
    website: "https://www.nitrkl.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Amrita School of Engineering",
    city: "Coimbatore",
    state: "Tamil Nadu",
    nirfRank: 17,
    nirfScore: 65.91,
    fees: 260000,
    averagePackage: 780000,
    rating: 4.1,
    overview: "Amrita School of Engineering is private institution offering rich computer science programs and strong alignment with moral and value-based learning.",
    establishedYear: 1994,
    website: "https://www.amrita.edu",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Engineering Science and Technology (IIEST)",
    city: "Howrah",
    state: "West Bengal",
    nirfRank: 18,
    nirfScore: 65.12,
    fees: 135000,
    averagePackage: 1080000,
    rating: 4.3,
    overview: "IIEST Shibpur is the second oldest engineering college in India, established in 1856. It is a highly respected public engineering institution.",
    establishedYear: 1856,
    website: "https://www.iiests.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Warangal",
    city: "Warangal",
    state: "Telangana",
    nirfRank: 19,
    nirfScore: 64.75,
    fees: 148000,
    averagePackage: 1590000,
    rating: 4.5,
    overview: "NIT Warangal is renowned for its academic quality, extremely competitive admissions via JEE Mains, and stellar core placement ratios.",
    establishedYear: 1959,
    website: "https://www.nitw.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    city: "Patiala",
    state: "Punjab",
    nirfRank: 20,
    nirfScore: 63.91,
    fees: 380000,
    averagePackage: 980000,
    rating: 4.3,
    overview: "Thapar Institute is a premier private university in Patiala, recognized for its modern campus, collaborations with Trinity College Dublin, and top placements.",
    establishedYear: 1956,
    website: "https://www.thapar.edu",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Indore",
    city: "Indore",
    state: "Madhya Pradesh",
    nirfRank: 21,
    nirfScore: 63.22,
    fees: 225000,
    averagePackage: 1710000,
    rating: 4.5,
    overview: "IIT Indore is situated in Madhya Pradesh, featuring advanced infrastructure and research opportunities, especially in Astrophysics and Machine Learning.",
    establishedYear: 2009,
    website: "https://www.iiti.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Birla Institute of Technology and Science (BITS) Pilani",
    city: "Pilani",
    state: "Rajasthan",
    nirfRank: 22,
    nirfScore: 62.81,
    fees: 480000,
    averagePackage: 1560000,
    rating: 4.7,
    overview: "Renowned private university with a 'No Attendance Policy' and dual-degree options, fostering high entrepreneurial spirit and top-tier placements.",
    establishedYear: 1964,
    website: "https://www.bits-pilani.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Mandi",
    city: "Mandi",
    state: "Himachal Pradesh",
    nirfRank: 23,
    nirfScore: 62.15,
    fees: 218000,
    averagePackage: 1500000,
    rating: 4.4,
    overview: "IIT Mandi is nestled in the serene Kamand Valley in Himachal Pradesh. It has unique coursework and focuses heavily on engineering solutions for mountain environments.",
    establishedYear: 2009,
    website: "https://www.iitmandi.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Ropar",
    city: "Rupnagar",
    state: "Punjab",
    nirfRank: 24,
    nirfScore: 61.54,
    fees: 220000,
    averagePackage: 1580000,
    rating: 4.3,
    overview: "IIT Ropar stands on the banks of the Sutlej River, providing exceptional research programs and advanced computer science infrastructures.",
    establishedYear: 2008,
    website: "https://www.iitrpr.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Technology (IIT) Gandhinagar",
    city: "Gandhinagar",
    state: "Gujarat",
    nirfRank: 25,
    nirfScore: 60.92,
    fees: 215000,
    averagePackage: 1610000,
    rating: 4.4,
    overview: "IIT Gandhinagar is situated in Gujarat's capital, focused on interdisciplinary curriculums and high international student exchange exposures.",
    establishedYear: 2008,
    website: "https://www.iitgn.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Jamia Millia Islamia (Faculty of Engineering)",
    city: "New Delhi",
    state: "Delhi",
    nirfRank: 26,
    nirfScore: 60.31,
    fees: 16000,
    averagePackage: 820000,
    rating: 4.3,
    overview: "Jamia Millia Islamia offers highly rated engineering courses at low tuition rates, drawing students nationwide for its top placements.",
    establishedYear: 1920,
    website: "https://www.jmi.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Siksha 'O' Anusandhan",
    city: "Bhubaneswar",
    state: "Odisha",
    nirfRank: 27,
    nirfScore: 59.82,
    fees: 220000,
    averagePackage: 630000,
    rating: 4.0,
    overview: "A highly accredited private university in Odisha, popular for its modern campus, library resources, and technology programs.",
    establishedYear: 2007,
    website: "https://www.soa.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Birla Institute of Technology (BIT) Mesra",
    city: "Ranchi",
    state: "Jharkhand",
    nirfRank: 28,
    nirfScore: 59.15,
    fees: 280000,
    averagePackage: 960000,
    rating: 4.2,
    overview: "BIT Mesra Ranchi is a highly respected deemed university, boasting a historical campus and an excellent alumni network in IT and manufacturing.",
    establishedYear: 1955,
    website: "https://www.bitmesra.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Delhi Technological University (DTU)",
    city: "New Delhi",
    state: "Delhi",
    nirfRank: 29,
    nirfScore: 58.74,
    fees: 190000,
    averagePackage: 1510000,
    rating: 4.6,
    overview: "Formerly Delhi College of Engineering (DCE), DTU is one of the oldest and most competitive engineering colleges in Delhi, yielding massive tech packages.",
    establishedYear: 1941,
    website: "http://www.dtu.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Calicut",
    city: "Calicut",
    state: "Kerala",
    nirfRank: 30,
    nirfScore: 58.12,
    fees: 142000,
    averagePackage: 1250000,
    rating: 4.4,
    overview: "NIT Calicut is located in Kerala, known for its lush green setting and top-notch engineering curricula drawing top JEE scorers.",
    establishedYear: 1961,
    website: "http://www.nitc.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "SASTRA Deemed University",
    city: "Thanjavur",
    state: "Tamil Nadu",
    nirfRank: 31,
    nirfScore: 57.65,
    fees: 160000,
    averagePackage: 680000,
    rating: 4.1,
    overview: "SASTRA is a prominent private university in Tamil Nadu, recognized for high academic discipline and good technology placements.",
    establishedYear: 1984,
    website: "https://www.sastra.edu",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Indian Institute of Information Technology (IIIT) Allahabad",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    nirfRank: 32,
    nirfScore: 57.11,
    fees: 200000,
    averagePackage: 2185000,
    rating: 4.7,
    overview: "IIIT Allahabad is a premium institute focused on Information Technology and electronics, famed for its massive coding culture and stellar tech placements.",
    establishedYear: 1999,
    website: "https://www.iiita.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Kalinga Institute of Industrial Technology (KIIT)",
    city: "Bhubaneswar",
    state: "Odisha",
    nirfRank: 33,
    nirfScore: 56.54,
    fees: 350000,
    averagePackage: 750000,
    rating: 4.2,
    overview: "KIIT is a massive private university in Odisha, celebrated for its expansive campus architecture, global collaborations, and high placements.",
    establishedYear: 1992,
    website: "https://kiit.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Aligarh Muslim University (AMU)",
    city: "Aligarh",
    state: "Uttar Pradesh",
    nirfRank: 34,
    nirfScore: 56.12,
    fees: 35000,
    averagePackage: 620000,
    rating: 4.2,
    overview: "Zakir Husain College of Engineering & Technology is the engineering wing of AMU, boasting a historical legacy and strong alumni connections.",
    establishedYear: 1920,
    website: "https://www.amu.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "SSN College of Engineering",
    city: "Chennai",
    state: "Tamil Nadu",
    nirfRank: 35,
    nirfScore: 55.78,
    fees: 115000,
    averagePackage: 720000,
    rating: 4.3,
    overview: "Founded by Shiv Nadar, SSN is highly regarded in Tamil Nadu for its research culture, beautiful green campus, and good corporate placements.",
    establishedYear: 1996,
    website: "https://www.ssn.edu.in",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "International Institute of Information Technology (IIIT) Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    nirfRank: 36,
    nirfScore: 55.24,
    fees: 360000,
    averagePackage: 3000000,
    rating: 4.9,
    overview: "IIIT Hyderabad is a premier research university, world-renowned for its coding achievements (ACM ICPC), high research index, and unmatched average packages.",
    establishedYear: 1998,
    website: "https://www.iiit.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Durgapur",
    city: "Durgapur",
    state: "West Bengal",
    nirfRank: 37,
    nirfScore: 54.83,
    fees: 138000,
    averagePackage: 1150000,
    rating: 4.2,
    overview: "NIT Durgapur is a highly ranked public engineering institution, offering a massive campus and quality research facilities in steel-related and computing fields.",
    establishedYear: 1960,
    website: "http://www.nitdgp.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Silchar",
    city: "Silchar",
    state: "Assam",
    nirfRank: 38,
    nirfScore: 54.32,
    fees: 135000,
    averagePackage: 1100000,
    rating: 4.1,
    overview: "NIT Silchar is known for its serene setting in Assam and high placement achievements in engineering and software streams.",
    establishedYear: 1967,
    website: "http://www.nits.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Visvesvaraya National Institute of Technology (VNIT)",
    city: "Nagpur",
    state: "Maharashtra",
    nirfRank: 39,
    nirfScore: 53.91,
    fees: 145000,
    averagePackage: 1210000,
    rating: 4.3,
    overview: "VNIT Nagpur is located in central India, offering highly respected core engineering branches and computer applications placements.",
    establishedYear: 1960,
    website: "http://www.vnit.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Malaviya National Institute of Technology (MNIT) Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    nirfRank: 40,
    nirfScore: 53.43,
    fees: 140000,
    averagePackage: 1240000,
    rating: 4.3,
    overview: "MNIT Jaipur is located in the beautiful city of Jaipur, offering outstanding academic labs, design centers, and stable placements.",
    establishedYear: 1963,
    website: "http://www.mnit.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Motilal Nehru National Institute of Technology (MNNIT)",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    nirfRank: 41,
    nirfScore: 52.92,
    fees: 146000,
    averagePackage: 1350000,
    rating: 4.4,
    overview: "MNNIT Allahabad is heavily reputed for its high software engineering placement ratios, securing placements in top global MNCs.",
    establishedYear: 1961,
    website: "http://www.mnnit.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "PSG College of Technology",
    city: "Coimbatore",
    state: "Tamil Nadu",
    nirfRank: 42,
    nirfScore: 52.51,
    fees: 85000,
    averagePackage: 750000,
    rating: 4.4,
    overview: "PSG Tech is a legendary private-aided institution in Coimbatore, recognized for industrial collaborations and top core placement outputs.",
    establishedYear: 1951,
    website: "http://www.psgtech.edu",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Punjab Engineering College (PEC)",
    city: "Chandigarh",
    state: "Chandigarh",
    nirfRank: 43,
    nirfScore: 52.02,
    fees: 172000,
    averagePackage: 1320000,
    rating: 4.3,
    overview: "PEC Chandigarh has a glorious history (alma mater of astronaut Kalpana Chawla). It is a premier deemed university with strong industrial bindings.",
    establishedYear: 1921,
    website: "http://www.pec.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Kurukshetra",
    city: "Kurukshetra",
    state: "Haryana",
    nirfRank: 44,
    nirfScore: 51.65,
    fees: 140000,
    averagePackage: 1200000,
    rating: 4.2,
    overview: "NIT Kurukshetra is a prominent public engineering college in Haryana, boasting strong labs and reliable corporate placements.",
    establishedYear: 1963,
    website: "http://www.nitkkr.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Jalandhar",
    city: "Jalandhar",
    state: "Punjab",
    nirfRank: 45,
    nirfScore: 51.21,
    fees: 138000,
    averagePackage: 1160000,
    rating: 4.1,
    overview: "NIT Jalandhar offers high-quality engineering courses in Punjab, supporting students with advanced engineering workshops.",
    establishedYear: 1987,
    website: "http://www.nitj.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "Sardar Vallabhbhai National Institute of Technology (SVNIT)",
    city: "Surat",
    state: "Gujarat",
    nirfRank: 46,
    nirfScore: 50.84,
    fees: 145000,
    averagePackage: 1235000,
    rating: 4.2,
    overview: "SVNIT Surat is a premier public university in Gujarat, widely known for its Chemical and Civil Engineering research contributions.",
    establishedYear: 1961,
    website: "http://www.svnit.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Meghalaya",
    city: "Shillong",
    state: "Meghalaya",
    nirfRank: 47,
    nirfScore: 50.31,
    fees: 135000,
    averagePackage: 1010000,
    rating: 4.1,
    overview: "NIT Meghalaya is located in Shillong, boasting a highly scenic environment and a growing reputation for core placement branches.",
    establishedYear: 2010,
    website: "http://nitmeghalaya.in",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Raipur",
    city: "Raipur",
    state: "Chhattisgarh",
    nirfRank: 48,
    nirfScore: 49.95,
    fees: 136000,
    averagePackage: 980000,
    rating: 4.1,
    overview: "NIT Raipur is one of the largest technology centers in central India, offering a historical legacy of engineering education.",
    establishedYear: 1956,
    website: "http://www.nitrr.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1607013407627-6ee814329547?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Srinagar",
    city: "Srinagar",
    state: "Jammu & Kashmir",
    nirfRank: 49,
    nirfScore: 49.53,
    fees: 140000,
    averagePackage: 910000,
    rating: 4.0,
    overview: "NIT Srinagar is situated on the banks of the Dal Lake. It has historical engineering research centers and strong regional importance.",
    establishedYear: 1960,
    website: "http://www.nitsri.net",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
  },
  {
    name: "National Institute of Technology (NIT) Patna",
    city: "Patna",
    state: "Bihar",
    nirfRank: 50,
    nirfScore: 49.02,
    fees: 138000,
    averagePackage: 1020000,
    rating: 4.1,
    overview: "NIT Patna has its roots in the Bihar School of Engineering, established in 1886, making it the 6th oldest engineering education hub in India.",
    establishedYear: 1886,
    website: "http://www.nitp.ac.in",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600",
  }
];

const popularCourses = [
  { name: "B.Tech Computer Science and Engineering", duration: "4 Years", degreeType: "B.Tech" },
  { name: "B.Tech Electronics and Communication Engineering", duration: "4 Years", degreeType: "B.Tech" },
  { name: "B.Tech Mechanical Engineering", duration: "4 Years", degreeType: "B.Tech" },
  { name: "B.Tech Electrical Engineering", duration: "4 Years", degreeType: "B.Tech" },
  { name: "B.Tech Civil Engineering", duration: "4 Years", degreeType: "B.Tech" },
  { name: "M.Tech Computer Science", duration: "2 Years", degreeType: "M.Tech" }
];

const reviewers = [
  "Rahul Sharma", "Anjali Nair", "Vikram Malhotra", "Siddharth Verma", "Ananya Iyer",
  "Rajesh Kumar", "Priya Patel", "Amit Singh", "Sneha Rao", "Rohan Mehta",
  "Neha Gupta", "Aditya Joshi", "Divya Deshmukh", "Karan Malhotra", "Pooja Reddy"
];

const generalComments = [
  "Excellent placements and research opportunities. The infrastructure is top-notch.",
  "Outstanding faculty guidance. Professors are extremely helpful for research work.",
  "Vibrant campus life and great peer environment. The coding culture is amazing.",
  "Highly competitive environment but provides immense industry exposure and support.",
  "Decent library resources and labs. Placements are solid, especially for core branches.",
  "Very active clubs and tech fests. Placements are great but the workload is rigorous.",
  "Beautiful campus with supportive professors. The peer group consists of top minds.",
  "Outstanding ROI compared to other private institutions. High internship options."
];

async function main() {
  console.log("Cleaning database...");
  await prisma.course.deleteMany();
  await prisma.review.deleteMany();
  await prisma.college.deleteMany();


  console.log("Seeding colleges, courses, and reviews...");
  
  for (const item of collegesData) {
    const college = await prisma.college.create({
      data: {
        name: item.name,
        city: item.city,
        state: item.state,
        nirfRank: item.nirfRank,
        nirfScore: item.nirfScore,
        fees: item.fees,
        averagePackage: item.averagePackage,
        rating: item.rating,
        overview: item.overview,
        establishedYear: item.establishedYear,
        website: item.website,
        imageUrl: item.imageUrl,
      }
    });

    // Create 3-4 random courses for each college from the popular courses template
    const shuffled = [...popularCourses].sort(() => 0.5 - Math.random());
    const selectedCourses = shuffled.slice(0, 3 + Math.floor(Math.random() * 2)); // 3 to 4 courses

    for (const courseItem of selectedCourses) {
      await prisma.course.create({
        data: {
          name: courseItem.name,
          duration: courseItem.duration,
          degreeType: courseItem.degreeType,
          collegeId: college.id
        }
      });
    }

    // Create 5 to 6 reviews for each college
    const reviewsCount = 5 + Math.floor(Math.random() * 2); // 5 to 6 reviews
    const shuffledReviewers = [...reviewers].sort(() => 0.5 - Math.random());
    const shuffledComments = [...generalComments].sort(() => 0.5 - Math.random());

    for (let i = 0; i < reviewsCount; i++) {
      const rating = parseFloat((4.0 + Math.random() * 1.0).toFixed(1));
      await prisma.review.create({
        data: {
          collegeId: college.id,
          userName: shuffledReviewers[i % shuffledReviewers.length],
          rating: rating,
          comment: shuffledComments[i % shuffledComments.length],
        }
      });
    }
  }
  console.log("Seeding completed successfully! Created 50 colleges, related courses, and reviews.");

}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
